import React from 'react';
import { Link } from 'react-router-dom';

export function PrivacyPage() {
  return (
    <>
      <style>{`
        .legal-page {
          min-height: 100vh;
          background: #070b14;
          color: #cbd5e1;
          font-family: inherit;
        }

        .legal-header {
          display: flex;
          align-items: center;
          padding: 20px clamp(20px, 5vw, 48px);
          border-bottom: 1px solid rgba(99, 102, 241, 0.1);
          background: rgba(7, 11, 20, 0.95);
        }

        .legal-header-brand {
          display: flex;
          align-items: center;
          gap: 10px;
          text-decoration: none;
        }

        .legal-header-logo {
          width: 30px;
          height: 30px;
          background: linear-gradient(135deg, #6366f1, #a855f7);
          border-radius: 7px;
          display: flex;
          align-items: center;
          justify-content: center;
          box-shadow: 0 0 12px rgba(99, 102, 241, 0.35);
          flex-shrink: 0;
        }

        .legal-header-wordmark {
          font-size: 1rem;
          font-weight: 800;
          letter-spacing: -0.03em;
          background: linear-gradient(135deg, #f0f4ff 0%, #a5b4fc 100%);
          -webkit-background-clip: text;
          -webkit-text-fill-color: transparent;
          background-clip: text;
        }

        .legal-content {
          max-width: 760px;
          margin: 0 auto;
          padding: clamp(40px, 6vw, 80px) clamp(20px, 5vw, 48px);
        }

        .legal-title {
          font-size: clamp(1.75rem, 4vw, 2.5rem);
          font-weight: 800;
          letter-spacing: -0.03em;
          color: #f0f4ff;
          margin: 0 0 8px;
        }

        .legal-updated {
          font-size: 0.875rem;
          color: #475569;
          margin: 0 0 48px;
        }

        .legal-section {
          margin-bottom: 40px;
        }

        .legal-section h2 {
          font-size: 1.125rem;
          font-weight: 700;
          color: #e2e8f0;
          margin: 0 0 12px;
        }

        .legal-section p {
          font-size: 0.9375rem;
          line-height: 1.75;
          color: #94a3b8;
          margin: 0 0 12px;
        }

        .legal-section p:last-child {
          margin-bottom: 0;
        }
      `}</style>

      <div className="legal-page">
        <header className="legal-header">
          <Link to="/" className="legal-header-brand" aria-label="CogniSync home">
            <div className="legal-header-logo" aria-hidden="true">
              <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="white" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">
                <path d="M9.5 2A2.5 2.5 0 0 1 12 4.5v15a2.5 2.5 0 0 1-4.96-.46 2.5 2.5 0 0 1-2.96-3.08 3 3 0 0 1-.34-5.58 2.5 2.5 0 0 1 1.32-4.24 2.5 2.5 0 0 1 1.98-3A2.5 2.5 0 0 1 9.5 2Z"/>
                <path d="M14.5 2A2.5 2.5 0 0 0 12 4.5v15a2.5 2.5 0 0 0 4.96-.46 2.5 2.5 0 0 0 2.96-3.08 3 3 0 0 0 .34-5.58 2.5 2.5 0 0 0-1.32-4.24 2.5 2.5 0 0 0-1.98-3A2.5 2.5 0 0 0 14.5 2Z"/>
              </svg>
            </div>
            <span className="legal-header-wordmark">CogniSync</span>
          </Link>
        </header>

        <main className="legal-content">
          <h1 className="legal-title">Privacy Policy</h1>
          <p className="legal-updated">Last updated: January 1, 2025</p>

          <div className="legal-section">
            <h2>Data Collection</h2>
            <p>
              CogniSync is designed with your privacy as a first principle. We do not collect, store, or transmit any personal information, usage data, or document content to external servers. The application operates entirely within your browser environment.
            </p>
            <p>
              We do not use analytics trackers, advertising networks, or third-party data processors. No account registration is required to use CogniSync, and we have no mechanism to identify individual users.
            </p>
          </div>

          <div className="legal-section">
            <h2>Local Storage</h2>
            <p>
              All data generated by CogniSync, including your session history, cognitive profile preferences, annotations, and processed document summaries, is stored exclusively in your browser's local storage. This data never leaves your device.
            </p>
            <p>
              You can clear this data at any time by clearing your browser's local storage or site data for this domain. Uninstalling or clearing the application will permanently remove all locally stored information.
            </p>
          </div>

          <div className="legal-section">
            <h2>No Server Transmission</h2>
            <p>
              Documents you paste or upload into CogniSync are processed locally within your browser. No document content, summaries, key points, or derived data are sent to any server operated by CogniSync or any third party. Your intellectual property remains entirely under your control.
            </p>
            <p>
              If you choose to use an external AI API key (such as an OpenAI key) for enhanced processing, your document content will be transmitted directly to that provider under their respective privacy policy. CogniSync does not intermediate or log these requests.
            </p>
          </div>

          <div className="legal-section">
            <h2>Contact</h2>
            <p>
              If you have questions or concerns about this privacy policy or how CogniSync handles data, you can reach us through the project's GitHub repository. We are committed to transparency and will respond to privacy inquiries in a timely manner.
            </p>
          </div>
        </main>
      </div>
    </>
  );
}
