import React from 'react';
import { Link } from 'react-router-dom';

export function TermsPage() {
  return (
    <>
      <style>{`
        .legal-page {
          min-height: 100vh;
          background: #070b14;
          color: #cbd5e1;
          font-family: inherit;
        }

        .legal-header {
          display: flex;
          align-items: center;
          padding: 20px clamp(20px, 5vw, 48px);
          border-bottom: 1px solid rgba(99, 102, 241, 0.1);
          background: rgba(7, 11, 20, 0.95);
        }

        .legal-header-brand {
          display: flex;
          align-items: center;
          gap: 10px;
          text-decoration: none;
        }

        .legal-header-logo {
          width: 30px;
          height: 30px;
          background: linear-gradient(135deg, #6366f1, #a855f7);
          border-radius: 7px;
          display: flex;
          align-items: center;
          justify-content: center;
          box-shadow: 0 0 12px rgba(99, 102, 241, 0.35);
          flex-shrink: 0;
        }

        .legal-header-wordmark {
          font-size: 1rem;
          font-weight: 800;
          letter-spacing: -0.03em;
          background: linear-gradient(135deg, #f0f4ff 0%, #a5b4fc 100%);
          -webkit-background-clip: text;
          -webkit-text-fill-color: transparent;
          background-clip: text;
        }

        .legal-content {
          max-width: 760px;
          margin: 0 auto;
          padding: clamp(40px, 6vw, 80px) clamp(20px, 5vw, 48px);
        }

        .legal-title {
          font-size: clamp(1.75rem, 4vw, 2.5rem);
          font-weight: 800;
          letter-spacing: -0.03em;
          color: #f0f4ff;
          margin: 0 0 8px;
        }

        .legal-updated {
          font-size: 0.875rem;
          color: #475569;
          margin: 0 0 48px;
        }

        .legal-section {
          margin-bottom: 40px;
        }

        .legal-section h2 {
          font-size: 1.125rem;
          font-weight: 700;
          color: #e2e8f0;
          margin: 0 0 12px;
        }

        .legal-section p {
          font-size: 0.9375rem;
          line-height: 1.75;
          color: #94a3b8;
          margin: 0 0 12px;
        }

        .legal-section p:last-child {
          margin-bottom: 0;
        }
      `}</style>

      <div className="legal-page">
        <header className="legal-header">
          <Link to="/" className="legal-header-brand" aria-label="CogniSync home">
            <div className="legal-header-logo" aria-hidden="true">
              <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="white" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">
                <path d="M9.5 2A2.5 2.5 0 0 1 12 4.5v15a2.5 2.5 0 0 1-4.96-.46 2.5 2.5 0 0 1-2.96-3.08 3 3 0 0 1-.34-5.58 2.5 2.5 0 0 1 1.32-4.24 2.5 2.5 0 0 1 1.98-3A2.5 2.5 0 0 1 9.5 2Z"/>
                <path d="M14.5 2A2.5 2.5 0 0 0 12 4.5v15a2.5 2.5 0 0 0 4.96-.46 2.5 2.5 0 0 0 2.96-3.08 3 3 0 0 0 .34-5.58 2.5 2.5 0 0 0-1.32-4.24 2.5 2.5 0 0 0-1.98-3A2.5 2.5 0 0 0 14.5 2Z"/>
              </svg>
            </div>
            <span className="legal-header-wordmark">CogniSync</span>
          </Link>
        </header>

        <main className="legal-content">
          <h1 className="legal-title">Terms of Service</h1>
          <p className="legal-updated">Last updated: January 1, 2025</p>

          <div className="legal-section">
            <h2>Acceptable Use</h2>
            <p>
              CogniSync is provided as a free, browser-based study tool intended for personal educational use. You may use CogniSync to process documents, generate summaries, and organize study materials for lawful purposes. You agree not to use CogniSync to process content that infringes on third-party intellectual property rights or violates applicable laws.
            </p>
            <p>
              You are solely responsible for the content you input into CogniSync and for ensuring you have the right to process that content. CogniSync does not review, moderate, or retain any documents you process.
            </p>
          </div>

          <div className="legal-section">
            <h2>No Warranty</h2>
            <p>
              CogniSync is provided "as is" and "as available" without warranties of any kind, either express or implied. We make no representations or warranties regarding the accuracy, completeness, or reliability of any summaries, key points, or other outputs generated by the application.
            </p>
            <p>
              AI-generated content may contain errors or omissions. You should independently verify any information produced by CogniSync before relying on it for academic, professional, or other important purposes.
            </p>
          </div>

          <div className="legal-section">
            <h2>Limitation of Liability</h2>
            <p>
              To the fullest extent permitted by applicable law, CogniSync and its contributors shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of or inability to use the application, even if advised of the possibility of such damages.
            </p>
            <p>
              Our total liability to you for any claims arising from these terms or your use of CogniSync shall not exceed the amount you paid to use the service, which in the case of the free tier is zero.
            </p>
          </div>

          <div className="legal-section">
            <h2>Governing Law</h2>
            <p>
              These terms shall be governed by and construed in accordance with applicable law, without regard to conflict of law principles. Any disputes arising under these terms shall be resolved through good-faith negotiation before pursuing formal legal remedies.
            </p>
            <p>
              If any provision of these terms is found to be unenforceable, the remaining provisions will continue in full force and effect. Our failure to enforce any right or provision of these terms will not be considered a waiver of those rights.
            </p>
          </div>
        </main>
      </div>
    </>
  );
}
